name: chubb
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py311h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.13.1
      - flask==3.1.2
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - git-filter-repo==2.47.0
      - google==3.0.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.26.0
      - google-api-python-client==2.184.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-genai==1.43.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.75.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.3
      - numba==0.62.1
      - numpy==2.3.3
      - nvidia-nccl-cu12==2.28.3
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.0.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - requests==2.32.5
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - shap==0.48.0
      - six==1.17.0
      - slicer==0.0.8
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.13.3
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - torch==2.8.0+cpu
      - torchvision==0.23.0+cpu
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - xgboost==3.0.5
prefix: /home/nitin/miniconda3/envs/chubb
